### ISSUE TITLE
Polymorphic query not adding type on rails3.2.21

### ISSUE THREAD

**Issue by raivil** [activerecord-hackery/squeel#392] opened 2015-07-27 19:22 UTC
Hey,
I'm having a issue with a simple polymorphic query, where the type is not set.
I'm I missing something here?

Gem versions:
Rails  3.2.21
Squeel (1.2.3)
polyamorous (1.1.0)

```
class ActivityLog < ActiveRecord::Base
  belongs_to :loggable, polymorphic: true
  attr_accessible :loggable, :body
end

class PatientChat < ActiveRecord::Base
  belongs_to :patient
end
```

```
> ActivityLog.joins{ [loggable(PatientChat)] }
```

``` sql
SELECT "activity_logs".* FROM "activity_logs" 
INNER JOIN "patient_chats" ON "patient_chats"."id" = "activity_logs"."loggable_id"
```

**Comment by rogierslag** [comment] 2015-08-10 12:52
Seems a duplicate of https://github.com/activerecord-hackery/squeel/issues/369

**Closed** 2021-03-10 12:40 UTC
